version: "3.9"

networks:
  apps:

services:

  rabbitmq:
    image: rabbitmq:3.9.29-alpine
    restart: always
    ports:
      - "5672:5672"
    networks:
      - apps

  app:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    networks:
      - apps