version: "3.9"

networks:
  apps:

services:

  rabbitmq:
    image: rabbitmq:3.9.29-alpine
    restart: always
    ports:
      - "5672:5672"
    networks:
      - apps

  ms1:
    build: ./ms1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - apps

  ms2:
    build: ./ms2
    restart: always
    ports:
      - "3001:3001"
    networks:
      - apps