version: "3.9"

networks:
  apps:

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.29-alpine
    restart: always
    ports:
      - "5672:5672"
    networks:
      - apps

  ms1:
    container_name: ms1
    build: ./ms1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - apps

  ms2:
    container_name: ms2
    build: ./ms2
    restart: always
    ports:
      - "3001:3001"
    networks:
      - apps

  loki:
    container_name: loki
    image: grafana/loki:2.8.0
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      -   apps

  promtail:
    container_name: promtail
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - apps

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/provisioning-datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yml
    ports:
      - "3101:3000"
    networks:
      -   apps